name: dev
on:
  workflow_dispatch:
  push:
    tags:
      - '*-dev'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from main repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Checkout code from another repository
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.REPOSITORY }}
          path: './media_saber_flutter_3'
          ref: 'dev'
          token: ${{ secrets.PERSON_ACCESS_TOKEN }}

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.32.8'

      - name: Build APK
        run: |
          cd ./media_saber_flutter_3
          flutter pub get
          flutter build apk --release

      # 直接用 tag 作为版本号
      - name: Set version from tag
        run: |
          echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          echo "VERSION_NAME=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSON_ACCESS_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ env.VERSION_NAME }}
          draft: false
          prerelease: false
          
      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSON_ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./media_saber_flutter_3/build/app/outputs/flutter-apk/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive