name: Build and Release APK
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [main, dev]

    steps:
      # Checkout 主仓库
      - name: "[${{ matrix.branch }}] Checkout main repo"
        uses: actions/checkout@v3
        with:
          ref: main

      # Checkout Flutter 子仓库
      - name: "[${{ matrix.branch }}] Checkout Flutter repo"
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.REPOSITORY }}
          path: './media_saber_flutter_3'
          ref: ${{ matrix.branch }}
          token: ${{ secrets.PERSON_ACCESS_TOKEN }}

      # 设置 Flutter
      - name: "[${{ matrix.branch }}] Set up Flutter"
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.32.8'

      # 构建 APK
      - name: "[${{ matrix.branch }}] Build APK"
        run: |
          cd ./media_saber_flutter_3
          flutter pub get
          flutter build apk --release

      # 计算 APK 大小和 MD5
      - name: "[${{ matrix.branch }}] Calculate APK Size and MD5"
        id: calculate_apk
        run: |
          APK_PATH=./media_saber_flutter_3/build/app/outputs/flutter-apk/app-release.apk
          APK_SIZE_BYTES=$(stat -c%s "$APK_PATH")
          APK_SIZE=$((APK_SIZE_BYTES / 1024))
          APK_MD5=$(md5sum "$APK_PATH" | awk '{ print $1 }')
          echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV
          echo "APK_SIZE=$APK_SIZE" >> $GITHUB_ENV
          echo "APK_MD5=$APK_MD5" >> $GITHUB_ENV

      # 删除旧 dev release 和 tag
      - name: "[${{ matrix.branch }}] Delete old dev release and tag"
        if: matrix.branch == 'dev'
        run: |
          DEV_TAG="${{ github.ref_name }}-dev"
          echo "Cleaning old dev release and tag: $DEV_TAG"
          gh release delete "$DEV_TAG" -y || echo "No old release found"
          git push origin ":refs/tags/$DEV_TAG" || echo "No old tag found"
        env:
          GITHUB_TOKEN: ${{ secrets.PERSON_ACCESS_TOKEN }}

      # 创建 Release
      - name: "[${{ matrix.branch }}] Create Release"
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSON_ACCESS_TOKEN }}
        with:
          tag_name: ${{ matrix.branch == 'main' && github.ref_name || format('{0}-dev', github.ref_name) }}
          release_name: ${{ matrix.branch == 'main' && format('Release {0}', github.ref_name) || format('Dev Release {0}', github.ref_name) }}
          draft: false
          prerelease: ${{ matrix.branch == 'dev' }}

      # 上传 Release APK
      - name: "[${{ matrix.branch }}] Upload Release Asset"
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSON_ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./media_saber_flutter_3/build/app/outputs/flutter-apk/app-release.apk
          asset_name: ${{ matrix.branch == 'main' && 'app-release.apk' || 'app-release-dev.apk' }}
          asset_content_type: application/vnd.android.package-archive

      # 更新 version.json/version-dev.json
      - name: "[${{ matrix.branch }}] Update version JSON"
        run: |
          # 根据分支设置文件名和下载后缀
          if [ "${{ matrix.branch }}" == "main" ]; then
            VERSION_FILE="version.json"
            DOWNLOAD_SUFFIX=""
          else
            VERSION_FILE="version-dev.json"
            DOWNLOAD_SUFFIX="-dev"
          fi

          # 确保文件存在
          if [ ! -f $VERSION_FILE ]; then
            echo '{"versionName":"","downloadUrl":"","apkSize":0,"apkMd5":""}' > $VERSION_FILE
          fi

          VERSION_NAME=${{ github.ref_name }}
          DOWNLOAD_URL=https://github.com/${{ github.repository }}/releases/download/${VERSION_NAME}${DOWNLOAD_SUFFIX}/app-release${DOWNLOAD_SUFFIX}.apk

          # 更新 JSON
          jq ".versionName = \"$VERSION_NAME$DOWNLOAD_SUFFIX\" | .downloadUrl = \"$DOWNLOAD_URL\" | .apkSize = $APK_SIZE | .apkMd5 = \"$APK_MD5\"" $VERSION_FILE > version.tmp && mv version.tmp $VERSION_FILE

          # 配置 Git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add $VERSION_FILE
          git commit -m "Update $VERSION_FILE for release $VERSION_NAME$DOWNLOAD_SUFFIX" || echo "No changes to commit"

          # 安全 pull & push，避免非快进被拒绝
          git pull --rebase origin main
          git push origin main